# NUMPY 3

In [1]:
import numpy as np

In [2]:
np.array([2,4,56,422,32,1]) # 1d array

array([  2,   4,  56, 422,  32,   1])

In [3]:
a = np.array([2,4,56,422,32,1]) # vector
print(a)

[  2   4  56 422  32   1]


In [4]:
type(a)

numpy.ndarray

In [5]:
new = np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [6]:
# 3 D ---- # tensor 
np.array ([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [7]:
np.array([11,23,44],dtype = float)

array([11., 23., 44.])

In [8]:
np.array([11,23,44],dtype = bool) 

array([ True,  True,  True])

In [9]:
np.array([11,23,44],dtype = complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

# arrnge

In [10]:
np.arange(1,25) # 1-include ,25 - last one got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [11]:
np.arange(1,25,2) #strides-----> AL ternate numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# reshape

In [12]:
np.arange(1,11).reshape(5,2) # converted 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
np.arange(1,11).reshape(2,5) # converted 2 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
np.arange(1,13).reshape(3,4) # converted 3 rows  and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# ones & zeros

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.random.random((4,3))

array([[0.21247077, 0.38207156, 0.18886954],
       [0.60372109, 0.59620245, 0.40191446],
       [0.19786451, 0.5414221 , 0.11864457],
       [0.77538295, 0.68620187, 0.34541279]])

# linespace

In [169]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [170]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

In [174]:
np.linspace(2,12,6)

array([ 2.,  4.,  6.,  8., 10., 12.])

# identity

In [175]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [176]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Arrributes

In [22]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a2 = np.arange(12, dtype = float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [24]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim

In [25]:
a1.ndim

1

In [26]:
a2.ndim

2

# shape

In [27]:
a1.shape # 1D array has 10 item

(10,)

In [28]:
a2.shape # 3 rows and 4 columns

(3, 4)

In [29]:
a3.shape #first 2 says it consists of 2d arrays  2,2 gives n0.of rows column

(2, 2, 2)

# size

In [30]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a3.size 

8

In [32]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [33]:
a2.size

12

# item size

In [34]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a1.itemsize 

4

In [36]:
a2.itemsize

8

In [37]:
a3.itemsize

4

# dtype

In [38]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# changing data type

In [39]:
x = np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [40]:
x.astype(int)

array([33, 22,  2])

# Array operation

In [41]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [42]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# scalar operation

In [44]:
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [45]:
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [46]:
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [47]:
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [48]:
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

# relational operators

In [49]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
z2 > 2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

# Vector operation

In [52]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
z1 + z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [55]:
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [56]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [57]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array function

In [58]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[51., 52., 11.],
       [61.,  7., 48.],
       [53., 62., 63.]])

In [59]:
np.max(k1)

63.0

In [60]:
np.min(k1)

7.0

In [61]:
np.sum(k1)

408.0

In [62]:
np.prod(k1)

123777989951616.0

# in numpy

In [63]:
np.max(k1, axis = 1)

array([52., 61., 63.])

In [64]:
np.max(k1,axis = 0)

array([61., 62., 63.])

In [65]:
np.prod(k1,axis=0)

array([164883.,  22568.,  33264.])

# statistics related function

In [177]:
k1

array([[51., 52., 11.],
       [61.,  7., 48.],
       [53., 62., 63.]])

In [178]:
np.mean(k1)

45.333333333333336

In [179]:
k1.mean(axis=0)

array([55.        , 40.33333333, 40.66666667])

In [180]:
np.median(k1)

52.0

In [70]:
np.median(k1, axis = 1)

array([51., 48., 62.])

In [181]:
np.std(k1)

20.07209228976613

In [182]:
np.std(k1, axis = 0)

array([ 4.3204938 , 23.92116682, 21.85304454])

In [183]:
np.var(k1)

402.88888888888886

# Trignometry Functions

In [184]:
np.sin(k1) 

array([[ 0.67022918,  0.98662759, -0.99999021],
       [-0.96611777,  0.6569866 , -0.76825466],
       [ 0.39592515, -0.7391807 ,  0.1673557 ]])

In [185]:
np.cos(k1)

array([[ 0.7421542 , -0.16299078,  0.0044257 ],
       [-0.25810164,  0.75390225, -0.64014434],
       [-0.91828279,  0.67350716,  0.98589658]])

In [186]:
np.tan(k1)

array([[ 9.03086149e-01, -6.05327238e+00, -2.25950846e+02],
       [ 3.74316794e+00,  8.71447983e-01,  1.20012724e+00],
       [-4.31158197e-01, -1.09750978e+00,  1.69749752e-01]])

# dot product

In [189]:
s2 = np.arange(12).reshape(3,4)
s3 = np.arange(12,24).reshape(4,3)
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [192]:
np.dot(s2,s3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# log and exponents

In [193]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# round/floor/ceil

# 1.round

In [195]:
arr = np.array([1.2,2.7,3.5,4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 3. 4. 5.]


In [196]:
arr = np.array([1.234,2.567,3.891])
rounded_arr = np.round(arr,decimals=2)
print(rounded_arr)

[1.23 2.57 3.89]


In [197]:
np.round(np.random.random((2,3))*100)

array([[67.,  1., 62.],
       [40., 74., 96.]])

# 2.floor

In [198]:
arr = np.array([1.2,2.7,3.5,4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [85]:
np.floor(np.random.random((2,3))*100)

array([[77., 65., 45.],
       [56., 83., 14.]])

# ceil

In [199]:
arr = np.array([1.2,2.7,3.5,4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [202]:
np.ceil(np.random.random((2,3))*100)

array([[96., 90.,  4.],
       [30.,  2.,  4.]])

# Indexing and slicing

In [203]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [204]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [206]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# indexing on 1D array

In [207]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
p1[-1]

9

In [94]:
p1[0]

0

# indexing on 2D array

In [95]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
p2[1,2]

6

In [210]:
p2[2,3]

11

In [211]:
p2[1,0]

4

# indexing on 3D (Tensors)

In [212]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [213]:
p3[1,0,1]

5

In [101]:
p3[0,1,0]

2

In [214]:
p3[0,0,0]

0

In [103]:
p3[1,1,0]

6

# slicing

In [104]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
p1[2:5]

array([2, 3, 4])

In [106]:
p1[2:5:2]

array([2, 4])

# slicing on 2D

In [107]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
p2[0,:]

array([0, 1, 2, 3])

In [109]:
p2[:,2]

array([ 2,  6, 10])

In [110]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
p2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
p2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [114]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
p2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [116]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
p2[1]

array([4, 5, 6, 7])

In [118]:
p2[1,::3]

array([4, 7])

In [119]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [121]:
p2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [122]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [124]:
p2[0:2,1::2]

array([[1, 3],
       [5, 7]])

# slicing in 3D

In [125]:
p3 = np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [126]:
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [127]:
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [129]:
p3[0,1,:]

array([3, 4, 5])

In [130]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [131]:
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [132]:
p3[1,:,1]

array([10, 13, 16])

In [133]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [134]:
p3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [135]:
p3[2,1:]

array([[21, 22, 23],
       [24, 25, 26]])

In [136]:
p3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [137]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [138]:
p3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
p3[0::2,0]

array([[ 0,  1,  2],
       [18, 19, 20]])

In [140]:
p3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# iterating

In [141]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [143]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [145]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [146]:
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [147]:
for i in np.nditer(p3):
    print(i)
  

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [148]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [150]:
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [151]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [152]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

# Ravel

In [153]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [155]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [156]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [157]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [159]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [160]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [162]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting

In [215]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [216]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [165]:
np.hsplit(w1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [166]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [167]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# speed of List vs Numpy

### List

In [168]:
a = [i for i in range (10000000)]
b = [i for i in range (10000000,20000000)]

c = []

import time

start = time . time()
for i in range(len(a)):
    c.append(a[i]+b[i])
    
print(time.time()-start)

4.644662141799927


### Numpy