# NUMPY 3

In [170]:
import numpy as np

In [171]:
np.array([2,4,56,422,32,1]) # 1d array

array([  2,   4,  56, 422,  32,   1])

In [3]:
a = np.array([2,4,56,422,32,1]) # vector
print(a)

[  2   4  56 422  32   1]


In [172]:
type(a)

numpy.ndarray

In [173]:
new = np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [174]:
# 3 D ---- # tensor 
np.array ([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [175]:
np.array([11,23,44],dtype = float)

array([11., 23., 44.])

In [176]:
np.array([11,23,44],dtype = bool) 

array([ True,  True,  True])

In [177]:
np.array([11,23,44],dtype = complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

# arrnge

In [178]:
np.arange(1,25) # 1-include ,25 - last one got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [179]:
np.arange(1,25,2) #strides-----> AL ternate numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# reshape

In [180]:
np.arange(1,11).reshape(5,2) # converted 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [181]:
np.arange(1,11).reshape(2,5) # converted 2 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
np.arange(1,13).reshape(3,4) # converted 3 rows  and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# ones & zeros

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.random.random((4,3))

array([[0.82846338, 0.93031829, 0.210376  ],
       [0.53422932, 0.7550627 , 0.02898569],
       [0.19450237, 0.41950757, 0.74448485],
       [0.57839857, 0.50334478, 0.64350784]])

# linespace

In [18]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [19]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# identity

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Arrributes

In [22]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a2 = np.arange(12, dtype = float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [24]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim

In [25]:
a1.ndim

1

In [26]:
a2.ndim

2

# shape

In [27]:
a1.shape # 1D array has 10 item

(10,)

In [28]:
a2.shape # 3 rows and 4 columns

(3, 4)

In [29]:
a3.shape #first 2 says it consists of 2d arrays  2,2 gives n0.of rows column

(2, 2, 2)

# size

In [30]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a3.size 

8

In [32]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [33]:
a2.size

12

# item size

In [34]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a1.itemsize 

4

In [36]:
a2.itemsize

8

In [37]:
a3.itemsize

4

# dtype

In [38]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# changing data type

In [39]:
x = np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [40]:
x.astype(int)

array([33, 22,  2])

# Array operation

In [41]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [42]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# scalar operation

In [44]:
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [45]:
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [46]:
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [47]:
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [48]:
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

# relational operators

In [49]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
z2 > 2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

# Vector operation

In [52]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
z1 + z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [55]:
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [56]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [57]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array function

In [58]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[98., 57., 58.],
       [28., 74., 49.],
       [84., 88., 40.]])

In [59]:
np.max(k1)

98.0

In [60]:
np.min(k1)

28.0

In [61]:
np.sum(k1)

576.0

In [62]:
np.prod(k1)

9726054651371520.0

# in numpy

In [63]:
np.max(k1, axis = 1)

array([98., 74., 88.])

In [64]:
np.max(k1,axis = 0)

array([98., 88., 58.])

In [65]:
np.prod(k1,axis=0)

array([230496., 371184., 113680.])

# statistics related function

In [66]:
k1

array([[98., 57., 58.],
       [28., 74., 49.],
       [84., 88., 40.]])

In [67]:
np.mean(k1)

64.0

In [68]:
k1.mean(axis=0)

array([70., 73., 49.])

In [69]:
np.median(k1)

58.0

In [70]:
np.median(k1, axis = 1)

array([58., 49., 84.])

In [71]:
np.std(k1)

22.145980322497454

In [72]:
np.std(k1, axis = 0)

array([30.24345659, 12.67543556,  7.34846923])

In [73]:
np.var(k1)

490.44444444444446

# Trignometry Functions

In [74]:
np.sin(k1) 

array([[-0.57338187,  0.43616476,  0.99287265],
       [ 0.27090579, -0.98514626, -0.95375265],
       [ 0.73319032,  0.0353983 ,  0.74511316]])

In [75]:
np.cos(k1)

array([[-0.81928825,  0.89986683,  0.11918014],
       [-0.96260587,  0.17171734,  0.30059254],
       [-0.6800235 ,  0.99937328, -0.66693806]])

In [76]:
np.tan(k1)

array([[ 0.69985365,  0.48469923,  8.33085685],
       [-0.2814296 , -5.73702254, -3.17290855],
       [-1.07818381,  0.0354205 , -1.11721493]])

# dot product

In [77]:
s2 = np.arange(12).reshape(3,4)
s3 = np.arange(12,24).reshape(4,3)
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [79]:
np.dot(s2,s3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# log and exponents

In [80]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# round/floor/ceil

# 1.round

In [81]:
arr = np.array([1.2,2.7,3.5,4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 3. 4. 5.]


In [82]:
arr = np.array([1.234,2.567,3.891])
rounded_arr = np.round(arr,decimals=2)
print(rounded_arr)

[1.23 2.57 3.89]


In [83]:
np.round(np.random.random((2,3))*100)

array([[42., 63., 94.],
       [85., 36., 90.]])

# 2.floor

In [84]:
arr = np.array([1.2,2.7,3.5,4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [85]:
np.floor(np.random.random((2,3))*100)

array([[12., 13., 71.],
       [45., 59.,  0.]])

# ceil

In [86]:
arr = np.array([1.2,2.7,3.5,4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [87]:
np.ceil(np.random.random((2,3))*100)

array([[78., 84., 60.],
       [ 3., 32., 22.]])

# Indexing and slicing

In [88]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [89]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# indexing on 1D array

In [92]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
p1[-1]

9

In [94]:
p1[0]

0

# indexing on 2D array

In [95]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
p2[1,2]

6

In [97]:
p2[2,3]

11

In [98]:
p2[1,0]

4

# indexing on 3D (Tensors)

In [99]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [100]:
p3[1,0,1]

5

In [101]:
p3[0,1,0]

2

In [102]:
p3[0,0,0]

0

In [103]:
p3[1,1,0]

6

# slicing

In [104]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
p1[2:5]

array([2, 3, 4])

In [106]:
p1[2:5:2]

array([2, 4])

# slicing on 2D

In [107]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
p2[0,:]

array([0, 1, 2, 3])

In [109]:
p2[:,2]

array([ 2,  6, 10])

In [110]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
p2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
p2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [114]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
p2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [116]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
p2[1]

array([4, 5, 6, 7])

In [118]:
p2[1,::3]

array([4, 7])

In [119]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [121]:
p2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [122]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [124]:
p2[0:2,1::2]

array([[1, 3],
       [5, 7]])

# slicing in 3D

In [125]:
p3 = np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [126]:
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [127]:
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [129]:
p3[0,1,:]

array([3, 4, 5])

In [130]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [131]:
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [132]:
p3[1,:,1]

array([10, 13, 16])

In [133]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [134]:
p3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [135]:
p3[2,1:]

array([[21, 22, 23],
       [24, 25, 26]])

In [136]:
p3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [137]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [138]:
p3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
p3[0::2,0]

array([[ 0,  1,  2],
       [18, 19, 20]])

In [140]:
p3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# iterating

In [141]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [143]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [145]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [146]:
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [147]:
for i in np.nditer(p3):
    print(i)
  

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [148]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [150]:
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [151]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [152]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

# Ravel

In [153]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [155]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [156]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [157]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [159]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [160]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [162]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting

In [163]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [165]:
np.hsplit(w1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [166]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [167]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# speed of List vs Numpy

### List

In [168]:
a = [i for i in range (10000000)]
b = [i for i in range (10000000,20000000)]

c = []

import time

start = time . time()
for i in range(len(a)):
    c.append(a[i]+b[i])
    
print(time.time()-start)

4.165559530258179


### Numpy

In [169]:
import numpy as np

a = np. arange(10000000)
b = np. arange(100000000,20000000)

start =time.time()
c = a+b
print(time.time()-start)

ValueError: operands could not be broadcast together with shapes (10000000,) (0,) 

In [ ]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start =time.time()
c = a+b
print(time.time()-start)

In [ ]:
2.7065064907073975 / 0.02248692512512207

# Meomary used for list vs Numpy

# List

In [ ]:
p = [i for i in range(10000000)]

import sys

sys.getsizeof(p)

# Numpy

In [ ]:
R = np.arange(100000000)

sys.getsizeof(R)

In [ ]:
R = np.arange(10000000, dtype = np.int16)
sys.getsizeof(R)

## Adavance INdexing and Slicing

In [ ]:
w = np.arange(12).reshape(4,3)
w

In [ ]:
w[1,2]

In [ ]:
w[1:3]

In [ ]:
w[1:3 , 1:3]

### Fancy Indexing

In [ ]:
w

In [ ]:
w[[0,2,3]]

In [ ]:
z = np.arange(24).reshape(6,4)
z

In [ ]:
z[[0,2,3,5]]

In [ ]:
z[:,[0,2,3]]

#### Boolean indexing

In [ ]:
G = np.random.randint(1,100,24).reshape(6,4)
G

In [ ]:
G > 50

In [ ]:
G[G > 50]

In [ ]:
G%2 == 0

In [ ]:
G [(G > 50) & (G % 2 == 0)]

In [ ]:
G % 7 == 0

In [ ]:
G [~ (G % 7 == 0) ]

# Broadcasting

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)

In [ ]:
print(b)

In [ ]:
print(a+b)

In [ ]:
a = np.arange(12).reshape(3,4)
a = np.arange(3)

print(a)
print(b)

print(a+b)

In [ ]:
a = np.arange(3).reshape(1,3)
a = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

In [ ]:
a = np.arange(3).reshape(1,3)
a = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a+b)

In [ ]:
a = np.array([1])

b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

In [ ]:
a = np.arange(16).reshape(4,4)
a = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a+b)

In [ ]:
# Not Work
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)

# working with mathematical formulas

In [ ]:
k = np.arange(10)
k

In [ ]:
np.sum(k)

In [ ]:
np.sin(k)

#### sigmoid

In [ ]:
def sigmoid(array):
    return 1/(1+np.exp(-(array)))
k = np.arange(10)
sigmoid(k)

In [ ]:
k = np.arange(100)
sigmoid(k)

### mean squared error

In [ ]:
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [ ]:
actual

In [ ]:
predicted

In [ ]:
def mse (actual,predicted):
    return np.mean((actual-predicted)**2)
mse(actual,predicted)

In [ ]:
actual-predicted

In [ ]:
(actual-predicted)**2

In [ ]:
np.mean(actual-predicted)**2

## Working with missing vailues

In [ ]:
S = np.array([1,2,3,4,np.nan,6])
S

In [ ]:
np.isnan(S)

In [ ]:
S[np.isnan(S)]

In [ ]:
S[~np.isnan(S)]

## Plotting Graphs

In [ ]:
x = np.linspace(-10,10,100)
x

In [ ]:
y = x

In [ ]:
y

In [ ]:
x

In [ ]:
import matplotlib.pyplot as plt

plt.plot(x,y)

In [ ]:
x = np.linspace(-10,10,100)
y = np.sin(x)

plt.plot(x,y)

In [ ]:
x = np.linspace(-10,10,100)
y = x*np.log(x)

plt.plot(x,y)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Meshgrid

In [ ]:
x = np.linspace(0,10,100)
y = np.linspace(0,10,100)

In [ ]:
f = x**2+y**2

In [ ]:
plt.figure(figsize=(4,2))
plt.plot(f)
plt.show()

In [ ]:
x = np.arange(3)
y = np.arange(3)

In [ ]:
x

In [ ]:
y

In [ ]:
xv  ,yv = np.meshgrid(x,y)
xv

In [ ]:
yv

In [ ]:
yv

In [ ]:
p = np.linspace(-4,4,9)
v = np.linspace(-5,5,11)
print(p)
print(v)

In [ ]:
p_1, v_1 = np.meshgrid(p,v)
print(p_1)

In [ ]:
print(v_1)

## Numpy Meshgrid Creates Coordinates for grid system

In [ ]:
xv**2 + yv**2

In [ ]:
x = np.linspace(-2,2,100)
y = np.linspace(-1,1,100)
xv,yv = np.meshgrid(x, y)
f = np.exp(-xv**2-yv**2)

In [ ]:
plt.figure(figsize=(6, 3))
plt.pcolormesh(xv, yv, f, shading='auto')
plt.colorbar()
plt.grid()
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
def f(x, y):
    return np.where((x**2 + y**2 < 1), 1.0, 0.0)
    
x = np.linspace(-5, 5, 500)
y = np.linspace(-5, 5, 500)
xv, yv = np.meshgrid(x, y)
rectangular_mask = f(xv, yv)


plt.pcolormesh(xv, yv, rectangular_mask, shading='auto')
plt.colorbar()
plt.grid()
plt.show()

In [ ]:
x = np.linspace(-4,4,9)

In [ ]:
y = np.linspace(-5,5,11)

In [ ]:
x_1, y_1, = np.meshgrid(x,y)

In [ ]:
random_data = np.random.random((11, 9))
plt.contourf(x_1, y_1, random_data, cmap = 'jet')
plt.colorbar()
plt.show()

In [ ]:
sine = (np.sin(x_1**2 + y_1**2))/(x_1**2 + y_1**2)
plt.contourf(x_1, y_1, sine, cmap = 'jet')
plt.colorbar()
plt.show()

In [ ]:
x_1, y_1 = np.meshgrid(x, y, sparse = True)
x_1

In [ ]:
y_1

# np.sort

In [ ]:
a = np.random.randint(1,100,15)
a

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

In [ ]:
np.sort(a)

In [ ]:
np.sort(a) [::-1]

In [ ]:
np.sort(b)

In [ ]:
np.sort (b, axis = 0)

# np.append

In [ ]:
a

In [ ]:
np.append(a,200)

In [ ]:
b

In [ ]:
np.append(b, np.ones((b.shape[0],1)))

In [ ]:
np.append(b, np.random.random((b.shape[0],1)),axis=1)

# np.concatenate

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [ ]:
c

In [ ]:
d

In [ ]:
np.concatenate((c,d),axis=1)

# np.unique

In [ ]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

In [ ]:
np.unique(e)

## np.expand_dlims

In [ ]:
a

In [ ]:
a.shape

In [ ]:
np.expand_dims(a,axis = 1)

In [ ]:
np.expand_dims(a,axis =1).shape

#np.where

In [ ]:
a

In [ ]:
np.where(a>50)

In [ ]:
np.where(a>50,0,a)

In [ ]:
np.where(a%2 == 0,0,a)

# np.argmax

In [ ]:
a

In [ ]:
np.argmax(a)

In [ ]:
b

In [ ]:
np.argmax(b,axis = 0)

In [ ]:
a

In [ ]:
np.argmin(a)

# On Statistics

## np.cumsum

In [ ]:
a

In [ ]:
np.cumsum(a)

In [ ]:
b

In [ ]:
np.cumsum(b)

In [ ]:
np.cumsum(b, axis = 1)

In [ ]:
np.cumsum(b, axis = 0)

In [ ]:
a

In [ ]:
np.cumprod(a)

## np.percentile

In [ ]:
a

In [ ]:
np.percentile(a,100)

In [ ]:
np.percentile(a,50)

In [ ]:
np.median(a)

# np.histogram

In [ ]:
a

In [ ]:
np.histogram(a, bins=[10,20,30,40,50,60,70,80,90,100])

In [ ]:
np.histogram(a, bins = [0,50,100])

# np.corrcoef

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [ ]:
salary

In [ ]:
experience

In [ ]:
np.corrcoef(salary,experience)

## Utility function

In [ ]:
a

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

In [ ]:
a[np.isin(a,items)]

# np.flip

In [ ]:
a

In [ ]:
np.flip(a)

In [ ]:
b

In [ ]:
np.flip(b)

In [ ]:
np.flip(b,axis = 1)

In [ ]:
np.flip(b,axis = 0)

## np.put

In [ ]:
a

In [ ]:
np.put(a,[0,1],[110,530])

In [ ]:
a

# np.delete

In [ ]:
a

In [ ]:
np.delete(a,0)

In [ ]:
np.delete(a,[0,2,4])

#### set function

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [ ]:
np.union1d(m,n)

In [ ]:
np.intersect1d(m,n)

In [ ]:
np.setdiff1d(m,n)

In [ ]:
np.setdiff1d(n,m)

In [ ]:
np.setxor1d(m,n)

In [ ]:
np.in1d(m,1)

In [ ]:
np.in1d(m,10)

#### np.clip

In [ ]:
a

In [ ]:
np.clip(a, a_min=15, a_max = 50)

## np.swapaxes

In [ ]:
arr = np.array(([[1,2,3],[4,5,6]]))
swapped_arr = np.swapaxes(arr,0,1)

In [ ]:
arr

In [ ]:
swapped_arr

In [ ]:
print ("Original array:")
print(arr)

In [ ]:
print("swapped array:")