# NUMPY CODE

## 1.

In [1]:
import numpy as np

In [155]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr1 = arr.reshape(2,3,2)
newarr2 = arr.reshape(4,3)

print(newarr1)

print(newarr2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [156]:
newarr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [157]:
newarr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [158]:
newarr1 = [...,2]
print(newarr1)

[Ellipsis, 2]


In [6]:
newarr1 = [1,...]
print(newarr1)

[1, Ellipsis]


## 2.[]

In [159]:
import numpy as np
b = np.arange(0,20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [160]:
b1 = np.reshape(b,(5,4))
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [161]:
b1[-1]

array([16, 17, 18, 19])

In [162]:
b1[1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [163]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [164]:
b1>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [13]:
b1<15

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [14]:

a = np.array([ [ 0, 1, 2, 3, 4],[10,11,12,13,14],[20,21,22,23,24],[30,31,32,33,34] ])
c = np.array( [True,False,True,False] ) # boolean row selector
print(a)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [15]:
a[c,:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [16]:
d =  np.array([False,True,True,False,True])  # boolean column selector
a[:,d]

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24],
       [31, 32, 34]])

In [17]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [18]:
i = np.array([0, 1, 2, 1]) # array of indices for the first axis
j = np.array([1,2,3,4]) # array of indices for the second axis

In [19]:
a[i,j]

array([ 1, 12, 23, 14])

# 3.abs() & 
# 4.ABSOLUTE both are same Synonym for abs()

In [165]:
import numpy as np
ARR = np.arange(-4,5).reshape(3,3)
ARR

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [166]:
abs(ARR)

array([[4, 3, 2],
       [1, 0, 1],
       [2, 3, 4]])

In [167]:
ARR1 = 1.2 + 5j
ARR1

(1.2+5j)

In [168]:
abs(ARR1)

5.141984052872976

In [169]:
np.absolute(ARR1)

5.141984052872976

In [170]:
np.absolute([-10,-15])

array([10, 15])

# 5. accumulate

In [171]:
import numpy as np

In [172]:
A1 = np.arange(0,10)
print(A1)

[0 1 2 3 4 5 6 7 8 9]


In [173]:
np.add.accumulate(A1)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [174]:
A2 = np.arange(1,6)

In [175]:
np.add.accumulate(A2)

array([ 1,  3,  6, 10, 15])

In [176]:
AC = np.array([[1,2,3],[4,5,6]])
AC

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
np.add.accumulate(AC)

array([[1, 2, 3],
       [5, 7, 9]])

In [33]:
np.add.accumulate(AC)

array([[1, 2, 3],
       [5, 7, 9]])

# 6.add

In [178]:
import numpy as np

In [179]:
ar1 = [2,-6]
ar2 = [1, 3]
ar3 = [2.2, 8.7]
ar4 = [7,-3]
print(ar1,ar2,ar3,ar4)

[2, -6] [1, 3] [2.2, 8.7] [7, -3]


In [180]:
np.add(ar1,ar2)

array([ 3, -3])

In [181]:
np.add(ar3, ar4)

array([9.2, 5.7])

In [182]:
c1 = 5+2j

In [183]:
np.add(ar3, c1)

array([ 7.2+2.j, 13.7+2.j])

# 7.all

In [189]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
np.all(a>5)

False

In [191]:
np.all(a>=0)

True

In [192]:
b7 = np.array([True,False,True,True])

In [193]:
np.all(b7)

False

# allclose

In [194]:
np.allclose([0.1,0.003],[0.11,0.003])

False

In [195]:
np.allclose([0.1e10,1e-8],[1.00011e10,1e-9])

False

In [196]:
np.allclose([1e10,1e-8],[1.00001e10,1e-9])

True

# alltrue- same as all function

In [48]:
b = np.array([True, False, True, True])
np.alltrue(b)

False

In [197]:
a = np.array([1, 5, 2, 7])
np.alltrue(a >= 5)

False

In [198]:
np.alltrue(a>0)

True

## 10.angle

In [199]:

np.angle([5+3j, 1j, 1.0]) # in RADIAN UNIT

array([0.5404195 , 1.57079633, 0.        ])

In [200]:

np.angle([5+3j, 1j, 1.0], deg=True)# in Degree

array([30.96375653, 90.        ,  0.        ])

In [201]:

np.angle(1+1j,deg=False) # in RADIAN Unit

0.7853981633974483

# 11.any

In [202]:
c2 = np.array([True,False,True])

In [203]:
np.any(c2)

True

In [204]:
c3= np.arange(0,10)
c3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
any(c3>=5)

True

In [206]:
any(c3<10)

True

In [207]:
any(c3>20)

False

# 12.append

In [208]:

c3= np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

In [209]:
c3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
c5 = np.append(c3,10)
c5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [211]:
np.append(c5,('ABC', 1+2j))

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'ABC', '(1+2j)'],
      dtype='<U64')

In [212]:
c9 = np.arange(10,61,10)
c9

array([10, 20, 30, 40, 50, 60])

In [213]:

np.append(c9, (70, 80, 90))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [214]:
c10 = np.reshape(c9,(2,3))
c10

array([[10, 20, 30],
       [40, 50, 60]])

In [215]:
c11 = np.append(c10,[[70,80,90]],axis = 0)
c11

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [68]:
c13 = np.append(c11, [[100], [120], [130]], axis = 1) # AT COLUMN
c13

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 120],
       [ 70,  80,  90, 130]])

## 13.apply_along_axis

In [69]:
def func1(Q): #EX-1
    return (Q[0] + Q[-1])
abc = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
abc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.apply_along_axis(func1,0,abc)

array([ 8, 10, 12])

In [71]:
np.apply_along_axis(func1,1,abc)

array([ 4, 10, 16])

In [72]:
def func2(P): #2
    return (P[0] + P[-1])*2
abc1 = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
abc1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.apply_along_axis(func2,0,abc1)

array([16, 20, 24])

In [74]:
np.apply_along_axis(func2,1,abc1)

array([ 8, 20, 32])

# 14.aaply_over_axes()

In [75]:
D = np.arange(24)
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [76]:
D = np.reshape(D,(2,3,4))
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [77]:
DQ = np.apply_over_axes(np.sum, D, [0,2])
DQ

array([[[ 60],
        [ 92],
        [124]]])

# 15. Arrange

In [78]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
np.arange(11,0)

array([], dtype=int32)

In [80]:
np.arange(8, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [81]:
np.arange(3,30,9)

array([ 3, 12, 21])

# 16.arccos

In [82]:
np.arccosh([np.e, 10.0])

array([1.65745445, 2.99322285])

In [83]:
np.arccosh(1)

0.0

# 17.arccosh

In [84]:
np.arccosh([np.e, 10.0])

array([1.65745445, 2.99322285])

In [85]:

np.arccosh(1)

0.0

# arcsin

In [86]:
np.arcsin([1, -1, 0])

array([ 1.57079633, -1.57079633,  0.        ])

## 20 arctan

In [216]:

np.arctan([0, 1, -1])

array([ 0.        ,  0.78539816, -0.78539816])

## 21.arctan2

In [217]:
#Consider four points in different quadrants
x = np.array([-1, +1, +1, -1])
y = np.array([-1, -1, +1, +1])
np.arctan2(y, x) * 180 / np.pi # In Degree Unit

array([-135.,  -45.,   45.,  135.])

In [218]:
np.arctan2(y,x)

array([-2.35619449, -0.78539816,  0.78539816,  2.35619449])

In [90]:
np.arctan2([1., -1.],[0., 0.])

array([ 1.57079633, -1.57079633])

In [91]:
np.arctan2([0,1], [1,0])

array([0.        , 1.57079633])

# 22.arctanh

In [92]:

np.arctanh([0, -0.5])

array([ 0.        , -0.54930614])

## 23. argmax

In [93]:
J = np.array([0,11,95,2,-5,55])

In [94]:
np.argmax(J)

2

In [95]:
j1 = np.arange(6).reshape(2,3) + 10
j1

array([[10, 11, 12],
       [13, 14, 15]])

In [96]:
np.argmax(j1)

5

In [97]:
J2 = np.array([[1, 9, 0, 4], [2, 0, 8, -1]])

In [98]:
J2

array([[ 1,  9,  0,  4],
       [ 2,  0,  8, -1]])

In [99]:
np.argmax(J2, axis=0)

array([1, 0, 1, 0], dtype=int64)

In [100]:
np.argmax(J2, axis=1)

array([1, 2], dtype=int64)

# 24.argmin

In [101]:
d4 = np.array([0,11,95,2,-5,55])

In [102]:
np.argmin(d4)

4

In [103]:
d9 = np.arange(6).reshape(2,3) + 10
d9

array([[10, 11, 12],
       [13, 14, 15]])

In [104]:
np.argmin(d9)

0

In [105]:
da2 = np.array([[50,50,10],[60,10,40]])
da2

array([[50, 50, 10],
       [60, 10, 40]])

In [106]:
np.argmin(da2)

2

In [107]:
np.argmin(da2, axis=0)

array([0, 1, 0], dtype=int64)

In [108]:
np.argmin(da2, axis=1)

array([2, 1], dtype=int64)

# 25.argsoft

In [109]:
AB1 = np.array([2,0, 1, 5, 4, 1, 9])

In [110]:
np.argsort(AB1)

array([1, 2, 5, 0, 4, 3, 6], dtype=int64)

In [111]:
BQ = np.argsort(AB1)
BQ

array([1, 2, 5, 0, 4, 3, 6], dtype=int64)

In [112]:
AB1[BQ]

array([0, 1, 1, 2, 4, 5, 9])

In [113]:
aq1 = np.array([[8,4,1],[2,0,9]])
aq1

array([[8, 4, 1],
       [2, 0, 9]])

In [114]:
JQ1 = aq1.argsort(axis=0)
JQ1

array([[1, 1, 0],
       [0, 0, 1]], dtype=int64)

In [115]:
aq1 [JQ1,[[0,1,2],[0,1,2]]]

array([[2, 0, 1],
       [8, 4, 9]])

In [116]:
JQ1 = aq1.argsort(axis=1)  # sort along rows. Can use aq1.argsort(axis=-1) for last axis.
JQ1 

array([[2, 1, 0],
       [1, 0, 2]], dtype=int64)

# 26.array

In [117]:
np.array([1,2, 3.0])

array([1., 2., 3.])

In [118]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [119]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [120]:
np.array([1,2,3], ndmin=2)

array([[1, 2, 3]])

In [121]:
np.array(1, copy=0, subok=1, ndmin=1)

array([1])

In [122]:
np.array(1, copy=0, subok=1, ndmin=2)

array([[1]])

In [123]:
np.array(1, subok=1, ndmin=2)

array([[1]])

# 27.arrayrange 
## same as Synonym for arange

## 28.Array split

In [124]:
c4 = np.array([[1,2,3,4],[5,6,7,8]])
c4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [125]:
np.array_split(c4, 4, axis=1)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [126]:
np.array_split(c4,3,axis=1)

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [127]:
np.array_split(c4,[2,3], axis=1)

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

# 29.asarray

In [128]:
my_list = [1,3,5,7,9]
np.asarray(my_list)

array([1, 3, 5, 7, 9])

In [129]:
my_tuple = ([1,3,9], [8,2,6])
np.asarray(my_tuple)

array([[1, 3, 9],
       [8, 2, 6]])

In [130]:
m = np.matrix('1 2; 5 8')
m

matrix([[1, 2],
        [5, 8]])

In [131]:
B9 = np.asarray(m)
B9

array([[1, 2],
       [5, 8]])

In [132]:
m[0,1] = -190
m

matrix([[   1, -190],
        [   5,    8]])

In [133]:
B9

array([[   1, -190],
       [   5,    8]])

# 30 asanyarray

In [134]:
c7 = np.array([[1,2],[5,8]])
c7

array([[1, 2],
       [5, 8]])

In [135]:
mq = np.matrix('1 2; 5 8')
mq

matrix([[1, 2],
        [5, 8]])

In [136]:
np.asanyarray(c7)

array([[1, 2],
       [5, 8]])

In [137]:
np.asanyarray(mq)

matrix([[1, 2],
        [5, 8]])

In [138]:
my_tuple1 = ([1,3,9],[8,2,6])

In [139]:
np.asanyarray(my_tuple1)

array([[1, 3, 9],
       [8, 2, 6]])

# 31.asmatrix

In [140]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)# m is matrix type with same contents as x -- data is not copied
m

matrix([[1, 2],
        [3, 4]])

In [141]:
x[0,0] = 5
print(m)

[[5 2]
 [3 4]]


## 32.astype

In [142]:
x6 = np.array([1,2, 2.5])
x6

array([1. , 2. , 2.5])

In [143]:
x6.astype(int)

array([1, 2, 2])

In [144]:
x6.astype(None)

array([1. , 2. , 2.5])

# 33.atleast 1d

In [145]:
a01 = 1 # 0-d array
b01 = np.array([2,3]) # 1-d array
c01 = np.array([[4,5],[6,7]]) # 2-d array
d01 = np.arange(8).reshape(2,2,2) # 3-d array
d01

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [146]:
np.atleast_1d(a01,b01,c01,d01)

[array([1]),
 array([2, 3]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

# 34.atleast_2d()

In [147]:
a11 = 1 # 0-d array
b11 = np.array([2,3]) # 1-d array
c11 = np.array([[4,5],[6,7]]) # 2-d array
d11 = np.arange(8).reshape(2,2,2) # 3-d array
d11

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [148]:
np.atleast_2d(a11,b11,c11,d11)

[array([[1]]),
 array([[2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

## 35.atleast_3d()

In [149]:
f = 1 # 0-d array
g = np.array([2,3]) # 1-d array
h = np.array([[4,5],[6,7]]) # 2-d array
i = np.arange(8).reshape(2,2,2) # 3-d array
i

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [150]:
np.atleast_3d(f,g,h,i)

[array([[[1]]]),
 array([[[2],
         [3]]]),
 array([[[4],
         [5]],
 
        [[6],
         [7]]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

# 36 Average

In [151]:
bz = np.array([1,4,5,7,5])
bz

array([1, 4, 5, 7, 5])

In [152]:
np.average(bz)

4.4

In [153]:
w = np.array([0.1,0.2,0.5,0.2,0.2])

In [154]:
np.average(bz,weights=w)

4.833333333333333